[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"
ndarray = "0.15.6"
nalgebra = "0.32.2"
libc = "0.2.147"
serde = "1.0.171"
serde_json = "1.0.102"
serde_derive = "1.0.171"